In [1]:
from create_data import DumbCirc as dc
from dklsuq import DeepKernelSUQ as dklu
import matplotlib
import matplotlib.pyplot as plt

In [2]:
data_instance = dc(0.5, 0.5, 0.25)
fc, pc, tc = data_instance.create_dataset(4, 2, [50], [0.2], True)

In [3]:
import torch
fc, pc, tc = torch.tensor(fc), torch.tensor(pc), torch.tensor(tc)

/tmp/ipykernel_485496/2979240048.py:2: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /opt/conda/conda-bld/pytorch_1711403246168/work/torch/csrc/utils/tensor_new.cpp:275.)
  fc, pc, tc = torch.tensor(fc), torch.tensor(pc), torch.tensor(tc)


In [4]:
fc.size()

torch.Size([8, 140, 2])

In [5]:
pc.size()

torch.Size([8, 35, 2])

In [6]:
model = dklu(point_cloud=fc, partial_cloud=pc, test_partial=tc)

In [7]:
use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
model.set_device(device)

In [8]:
model.set_test_data(tc)

In [9]:
model.train()

tensor([[-0.1333, -0.3598, -1.2362,  ...,  0.1947, -1.0790, -0.2944],
        [-0.1395, -0.3647, -1.2353,  ...,  0.1920, -1.0807, -0.2930],
        [-0.1272, -0.3558, -1.2333,  ...,  0.1943, -1.0725, -0.2982],
        ...,
        [-0.1319, -0.3598, -1.2315,  ...,  0.1924, -1.0724, -0.2977],
        [-0.1293, -0.3566, -1.2372,  ...,  0.1957, -1.0773, -0.2957],
        [-0.1337, -0.3599, -1.2375,  ...,  0.1953, -1.0802, -0.2938]],
       grad_fn=<AddmmBackward0>)
tensor([[-0.2245, -0.1558, -0.6880,  ...,  0.0390, -0.2994, -0.4382],
        [-0.2267, -0.1623, -0.6761,  ...,  0.0410, -0.2939, -0.4322],
        [-0.2256, -0.1565, -0.6858,  ...,  0.0371, -0.3037, -0.4350],
        ...,
        [-0.2267, -0.1604, -0.6780,  ...,  0.0407, -0.2952, -0.4325],
        [-0.2269, -0.1602, -0.6783,  ...,  0.0400, -0.2962, -0.4321],
        [-0.2246, -0.1559, -0.6875,  ...,  0.0393, -0.2989, -0.4379]],
       grad_fn=<AddmmBackward0>)
tensor([[-0.2479,  0.0302, -0.3402,  ..., -0.0875, -0.1495, -0.162

/servers/ash/hdd-home3/dghosh/Documents/Thesis/1notebooks/dklsuq.py:117: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /opt/conda/conda-bld/pytorch_1711403246168/work/aten/src/ATen/native/TensorShape.cpp:3637.)
  + posterior_mean.T @ torch.linalg.inv(posterior_var) @ posterior_mean)


_LinAlgError: linalg.inv: The diagonal element 140 is zero, the inversion could not be completed because the input matrix is singular.