In [1]:
import torch

In [23]:
a = torch.randn((5, 5, 2))

In [139]:
e = torch.randn((5, 2))

In [145]:
c = torch.combinations(torch.arange(a.size(1)), r=2, with_replacement=True)

In [146]:
c

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [2, 2],
        [2, 3],
        [2, 4],
        [3, 3],
        [3, 4],
        [4, 4]])

In [147]:
x = a[:, None, :].expand(-1, len(c), -1, -1)

In [148]:
x.shape

torch.Size([5, 15, 5, 2])

In [149]:
idx = c[None].expand(len(x), -1, -1, -1)
idx.shape

torch.Size([5, 1, 15, 2])

In [150]:
x

tensor([[[[-0.6739, -1.8659],
          [-0.1574,  0.3765],
          [-0.3721,  0.1064],
          [-0.1036,  0.4388],
          [-0.7666, -1.4346]],

         [[-0.6739, -1.8659],
          [-0.1574,  0.3765],
          [-0.3721,  0.1064],
          [-0.1036,  0.4388],
          [-0.7666, -1.4346]],

         [[-0.6739, -1.8659],
          [-0.1574,  0.3765],
          [-0.3721,  0.1064],
          [-0.1036,  0.4388],
          [-0.7666, -1.4346]],

         [[-0.6739, -1.8659],
          [-0.1574,  0.3765],
          [-0.3721,  0.1064],
          [-0.1036,  0.4388],
          [-0.7666, -1.4346]],

         [[-0.6739, -1.8659],
          [-0.1574,  0.3765],
          [-0.3721,  0.1064],
          [-0.1036,  0.4388],
          [-0.7666, -1.4346]],

         [[-0.6739, -1.8659],
          [-0.1574,  0.3765],
          [-0.3721,  0.1064],
          [-0.1036,  0.4388],
          [-0.7666, -1.4346]],

         [[-0.6739, -1.8659],
          [-0.1574,  0.3765],
          [-0.3721,  0.1064]

In [151]:
e

tensor([[-1.2498,  1.2096],
        [-1.9910, -1.9841],
        [ 0.7411,  0.7746],
        [ 1.2702, -1.2817],
        [ 0.3249, -0.6083]])

In [152]:
for i in range(x.size(0)):
    print(i)
    for j in range(len(c)):
        print(torch.concat((x[i][j][c[j]].flatten(), e[i])))

0
tensor([-0.6739, -1.8659, -0.6739, -1.8659, -1.2498,  1.2096])
tensor([-0.6739, -1.8659, -0.1574,  0.3765, -1.2498,  1.2096])
tensor([-0.6739, -1.8659, -0.3721,  0.1064, -1.2498,  1.2096])
tensor([-0.6739, -1.8659, -0.1036,  0.4388, -1.2498,  1.2096])
tensor([-0.6739, -1.8659, -0.7666, -1.4346, -1.2498,  1.2096])
tensor([-0.1574,  0.3765, -0.1574,  0.3765, -1.2498,  1.2096])
tensor([-0.1574,  0.3765, -0.3721,  0.1064, -1.2498,  1.2096])
tensor([-0.1574,  0.3765, -0.1036,  0.4388, -1.2498,  1.2096])
tensor([-0.1574,  0.3765, -0.7666, -1.4346, -1.2498,  1.2096])
tensor([-0.3721,  0.1064, -0.3721,  0.1064, -1.2498,  1.2096])
tensor([-0.3721,  0.1064, -0.1036,  0.4388, -1.2498,  1.2096])
tensor([-0.3721,  0.1064, -0.7666, -1.4346, -1.2498,  1.2096])
tensor([-0.1036,  0.4388, -0.1036,  0.4388, -1.2498,  1.2096])
tensor([-0.1036,  0.4388, -0.7666, -1.4346, -1.2498,  1.2096])
tensor([-0.7666, -1.4346, -0.7666, -1.4346, -1.2498,  1.2096])
1
tensor([ 2.3543, -1.3906,  2.3543, -1.3906, -1.9910

In [127]:
a

tensor([[[-0.6739, -1.8659],
         [-0.1574,  0.3765],
         [-0.3721,  0.1064],
         [-0.1036,  0.4388],
         [-0.7666, -1.4346]],

        [[ 2.3543, -1.3906],
         [ 2.5524,  0.9049],
         [ 0.4959, -0.6001],
         [ 0.3402, -1.9756],
         [-1.6121,  1.5578]],

        [[ 0.5546,  0.9666],
         [-0.3232,  1.4323],
         [ 0.3522,  0.8644],
         [-0.8852, -0.9833],
         [-1.2670,  0.3992]],

        [[ 1.3296,  0.3499],
         [ 0.3760,  0.5044],
         [-1.2320,  1.6775],
         [-1.4320, -1.3125],
         [ 0.5550,  0.0609]],

        [[-0.7610,  0.5408],
         [ 0.3891, -0.5170],
         [-0.3454,  1.5764],
         [ 1.5243, -0.4862],
         [ 1.8933, -0.1243]]])

In [154]:
i,j = torch.triu_indices(len(c), len(c))

In [155]:
i 

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
         2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,
         7,  7,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9, 10, 10, 10,
        10, 10, 11, 11, 11, 11, 12, 12, 12, 13, 13, 14])