In [1]:
import torch

In [21]:
x = torch.randn(2, 10, 2)
y = torch.randn(2, 10)

In [70]:
y

tensor([[-0.0818, -1.2972, -0.4690,  0.7602, -0.6529,  0.5660, -1.3568,  0.7873,
          0.7186,  0.3805],
        [-0.0163,  0.3446, -0.1056, -2.3197,  0.1394, -0.1652, -0.3473, -2.2373,
         -0.1673,  1.9963]])

In [93]:
(0.01 * torch.randn(x.size()[:-1])).shape

torch.Size([2, 10])

In [87]:
l=y.unsqueeze(2).repeat(1, 1, 5)

In [89]:
l.reshape(l.size(0), -1)

tensor([[-0.0818, -0.0818, -0.0818, -0.0818, -0.0818, -1.2972, -1.2972, -1.2972,
         -1.2972, -1.2972, -0.4690, -0.4690, -0.4690, -0.4690, -0.4690,  0.7602,
          0.7602,  0.7602,  0.7602,  0.7602, -0.6529, -0.6529, -0.6529, -0.6529,
         -0.6529,  0.5660,  0.5660,  0.5660,  0.5660,  0.5660, -1.3568, -1.3568,
         -1.3568, -1.3568, -1.3568,  0.7873,  0.7873,  0.7873,  0.7873,  0.7873,
          0.7186,  0.7186,  0.7186,  0.7186,  0.7186,  0.3805,  0.3805,  0.3805,
          0.3805,  0.3805],
        [-0.0163, -0.0163, -0.0163, -0.0163, -0.0163,  0.3446,  0.3446,  0.3446,
          0.3446,  0.3446, -0.1056, -0.1056, -0.1056, -0.1056, -0.1056, -2.3197,
         -2.3197, -2.3197, -2.3197, -2.3197,  0.1394,  0.1394,  0.1394,  0.1394,
          0.1394, -0.1652, -0.1652, -0.1652, -0.1652, -0.1652, -0.3473, -0.3473,
         -0.3473, -0.3473, -0.3473, -2.2373, -2.2373, -2.2373, -2.2373, -2.2373,
         -0.1673, -0.1673, -0.1673, -0.1673, -0.1673,  1.9963,  1.9963,  1.9963,


In [26]:
a = x.unsqueeze(2).expand(-1, -1, 5, -1)
a.shape

torch.Size([2, 10, 5, 2])

In [49]:
a

tensor([[[[-0.3610, -0.4261],
          [-0.3610, -0.4261],
          [-0.3610, -0.4261],
          [-0.3610, -0.4261],
          [-0.3610, -0.4261]],

         [[-1.5209, -0.3781],
          [-1.5209, -0.3781],
          [-1.5209, -0.3781],
          [-1.5209, -0.3781],
          [-1.5209, -0.3781]],

         [[ 1.4344, -1.4839],
          [ 1.4344, -1.4839],
          [ 1.4344, -1.4839],
          [ 1.4344, -1.4839],
          [ 1.4344, -1.4839]],

         [[ 1.1517, -0.9763],
          [ 1.1517, -0.9763],
          [ 1.1517, -0.9763],
          [ 1.1517, -0.9763],
          [ 1.1517, -0.9763]],

         [[-0.4574,  0.1320],
          [-0.4574,  0.1320],
          [-0.4574,  0.1320],
          [-0.4574,  0.1320],
          [-0.4574,  0.1320]],

         [[ 0.8202,  0.1509],
          [ 0.8202,  0.1509],
          [ 0.8202,  0.1509],
          [ 0.8202,  0.1509],
          [ 0.8202,  0.1509]],

         [[-2.4004, -0.3327],
          [-2.4004, -0.3327],
          [-2.4004, -0.3327]

In [60]:
b = torch.empty(a.size())
for i in range(x.size(0)):
    points = x[i]
    for j, p in enumerate(points):
        dist = points.add(-p).pow(2).sum(dim=1)
        knn_indices = dist.topk(5, largest=False, sorted=False)[1]
        knn_points = points.gather(0, knn_indices.unsqueeze(-1).repeat(1,2))
        b[i][j] = knn_points - p

In [65]:
c= torch.concat((a,b), dim=3)
c

tensor([[[[-0.3610, -0.4261,  0.4920, -0.3324],
          [-0.3610, -0.4261, -0.0963,  0.5582],
          [-0.3610, -0.4261,  0.0000,  0.0000],
          [-0.3610, -0.4261, -1.1599,  0.0480],
          [-0.3610, -0.4261,  1.1813,  0.5770]],

         [[-1.5209, -0.3781, -0.4214, -0.5384],
          [-1.5209, -0.3781,  0.0000,  0.0000],
          [-1.5209, -0.3781, -0.8795,  0.0454],
          [-1.5209, -0.3781,  1.1599, -0.0480],
          [-1.5209, -0.3781,  1.0635,  0.5101]],

         [[ 1.4344, -1.4839, -0.6142,  1.6348],
          [ 1.4344, -1.4839, -1.3034,  0.7254],
          [ 1.4344, -1.4839,  0.0000,  0.0000],
          [ 1.4344, -1.4839, -0.2827,  0.5076],
          [ 1.4344, -1.4839, -1.7954,  1.0578]],

         [[ 1.1517, -0.9763, -1.0207,  0.2178],
          [ 1.1517, -0.9763,  0.0000,  0.0000],
          [ 1.1517, -0.9763,  0.2827, -0.5076],
          [ 1.1517, -0.9763, -0.3314,  1.1272],
          [ 1.1517, -0.9763, -1.5127,  0.5502]],

         [[-0.4574,  0.1320,  0.

In [69]:
c.reshape(c.size(0), c.size(1)*c.size(2), c.size(-1)).shape

torch.Size([2, 50, 4])

In [8]:
z = x * y [..., None]

In [13]:
z = torch.permute(z, (2, 0, 1))

In [23]:
torch.exp(-0.5*torch.cdist(z, z)).mean(dim=0)

tensor([[1.0000, 0.7330, 0.7301, 0.5627, 0.5227, 0.7554, 0.7758, 0.5971, 0.6453,
         0.8851, 0.8827, 0.5812, 0.6824, 0.6405, 0.6914, 0.7413, 0.6104, 0.4212,
         0.9032, 0.8981],
        [0.7330, 1.0000, 0.6280, 0.6124, 0.5738, 0.6218, 0.6648, 0.5298, 0.5260,
         0.6671, 0.6800, 0.5479, 0.5560, 0.5216, 0.5466, 0.6157, 0.4550, 0.3844,
         0.7655, 0.6714],
        [0.7301, 0.6280, 1.0000, 0.4663, 0.4275, 0.8350, 0.6944, 0.5392, 0.6198,
         0.7644, 0.6598, 0.6517, 0.6917, 0.6852, 0.7512, 0.7634, 0.6309, 0.3982,
         0.6596, 0.7660],
        [0.5627, 0.6124, 0.4663, 1.0000, 0.3940, 0.4812, 0.4745, 0.4908, 0.5008,
         0.5447, 0.5563, 0.5664, 0.4835, 0.4861, 0.4471, 0.5093, 0.4062, 0.2887,
         0.5814, 0.5362],
        [0.5227, 0.5738, 0.4275, 0.3940, 1.0000, 0.4599, 0.4954, 0.3882, 0.3874,
         0.4769, 0.5238, 0.4283, 0.3947, 0.3317, 0.3479, 0.4459, 0.3844, 0.3848,
         0.5242, 0.4842],
        [0.7554, 0.6218, 0.8350, 0.4812, 0.4599, 1.0000, 0.7

In [3]:
torch.tensor(torch.pi)

tensor(3.1416)

In [1]:
from create_data_dgcn_cc import Circ as cc

In [2]:
data_instance = cc(0.4, 0.4, 0.2, 26)

In [3]:
fpc, pc, lp, tc, lt = data_instance.create_dataset(5, 1, [100], [0.2], 10)

In [4]:
fpc.shape

(5, 224, 2)

In [5]:
pc.shape

(5, 56, 2)

In [6]:
tc.shape

(1, 56, 2)